# docker compose to spin up a local mssql database
# define your volume to be on this machine and put your database restore file in this.

version: "3.9"

services:
  labkey:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: labkey
    hostname: labkey
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Labkey1098!"
    volumes:
      - /home/nick/labkey/database:/labkey
    restart: unless-stopped
